exercise/m4-java-history_geek_exercises/src/main/java/com/techelevator/model/ChatMessage.java
package com.techelevator.model;

import java.time.Instant;
import java.time.LocalDateTime;
import java.time.ZoneOffset;
import java.util.Date;

public class ChatMessage {
	
	private Long id;
	private Long userID;
	private String message;
	private LocalDateTime sentDate;
	private String userName;
	
	public Long getID() {
		return id;
	}
	public void setID(Long id) {
		this.id = id;
	}
	// Required
	public Long getUserID() {
		return userID;
	}
	public void setUserID(Long userID) {
		this.userID = userID;
	}
	// Required
	public String getMessage() {
		return message;
	}
	public void setMessage(String message) {
		this.message = message;
	}
	public LocalDateTime getSentDate() {
		return sentDate;
	}
	public Date getSentDateAsDate() {
		Instant instant = sentDate.toInstant(ZoneOffset.of("-5"));
		return Date.from(instant);
	}
	public void setSentDate(LocalDateTime sentDate) {
		this.sentDate = sentDate;
	}
	// userName property is retrieved by joining with the users table
	public String getUserName() {
		return userName;
	}
	public void setUserName(String userName) {
		this.userName = userName;
	}

}

exercise/m4-java-history_geek_exercises/src/main/java/com/techelevator/controller/ChatController.java
package com.techelevator.controller;

import java.time.LocalDateTime;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.messaging.handler.annotation.MessageMapping;
import org.springframework.messaging.simp.SimpMessageHeaderAccessor;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.techelevator.model.ChatHistoryDAO;
import com.techelevator.model.ChatMessage;
import com.techelevator.model.User;
import com.techelevator.model.UserDAO;

@Controller
public class ChatController {
	
	@Autowired
	private ChatHistoryDAO chatRepository;
	
	@Autowired
	private UserDAO userRepository;
	
	@RequestMapping(value="/chat", method=RequestMethod.GET)
	public String index(Model model) {
		List<ChatMessage> messages = chatRepository.getChatMessages(20);
		
		model.addAttribute("messages", messages);
		return "chat/index";
	}
	
	@MessageMapping("/chat")
	//@PreAuthorize("isAuthorized()")
	public ChatMessage handleMessage(ChatMessage chatMessage, SimpMessageHeaderAccessor headerAccessor) {
		if(chatMessage != null && ! chatMessage.getMessage().isEmpty()) {
			
			 // Get the user who sent in the request
            User user = userRepository.getUser((String)headerAccessor.getSessionAttributes().get("email"));
            
            if(user != null) {
            	chatMessage.setUserID(user.getID());
            	chatMessage.setUserName(user.getEmail());
            }
            chatMessage.setSentDate(LocalDateTime.now());

            // Save the chat message
            chatRepository.saveChatMessage(chatMessage);

            return chatMessage;
        }
		
		return null;
	}

	public ChatHistoryDAO getChatRepository() {
		return chatRepository;
	}

	public void setChatRepository(ChatHistoryDAO chatRepository) {
		this.chatRepository = chatRepository;
	}

	public UserDAO getUserRepository() {
		return userRepository;
	}

	public void setUserRepository(UserDAO userRepository) {
		this.userRepository = userRepository;
	}
}

exercise/m4-java-history_geek_exercises/src/main/webapp/WEB-INF/jsp/chat/index.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>

<c:import url="/WEB-INF/jsp/common/header.jsp" />

<c:url value="/js" var="jsHref" />
<script src="${jsHref}/sockjs.min.js"></script>
<script src="${jsHref}/stomp.min.js"></script>
<script src="${jsHref}/exercises/websocket-exercises.js"></script>

<div id="chatroom">

    <div id="messages">
        <h3>History</h3>
        <!-- Messages go here -->
        <div id="history">
            <c:forEach items="${messages}" var="message">
                <p class="message">
                    <span class="username"><c:out value="${message.userName}"/></span>
                    <span class="time"><fmt:formatDate value="${message.sentDateAsDate}" pattern="h:mm a"/></span> <br />
                    <c:out value="${message.message}"/>
                </p>
            </c:forEach>
        </div>
        <div id="newMessageForm">
        	<form action="#" id="chatForm">
        		<textarea name="message"></textarea>
        		<button>Send</button>
        	</form>
        </div>
    </div>
    <div id="members">
        <h3>Active Members</h3>
        <!-- Members List goes here -->
        <ul>            
        </ul>
    </div>
</div>


<c:import url="/WEB-INF/jsp/common/footer.jsp" />